apiVersion: v1
kind: ConfigMap
metadata:
  name: v2ray-config
data:
  config.json: |
    {
      "dns": {},
      "stats": {},
      "policy": {
        "levels": {
          "0": {
            "handshake": 4,
            "connIdle": 300,
            "uplinkOnly": 2,
            "downlinkOnly": 5,
            "statsUserUplink": true,
            "statsUserDownlink": true,
            "bufferSize": 4
          }
        },
        "system": {
          "statsInboundUplink": true,
          "statsInboundDownlink": true
        }
      },
      "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
          {
            "type": "field",
            "protocol": ["bittorrent"],
            "outboundTag": "block"
          },
          {
            "type": "field",
            "ip": ["geoip:private"],
            "outboundTag": "block"
          }
        ]
      },
      "inbounds": [
        {
          "port": {{ .Values.v2ray.port }},
          "listen": "0.0.0.0",
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                "id": "{{ .Values.v2ray.uuid }}",
                "alterId": {{ .Values.v2ray.alterId }}
              }
            ]
          },
          "streamSettings": {
            "network": "{{ .Values.v2ray.network }}",
            "security": "{{ .Values.v2ray.security }}",
            "tcpSettings": {
              "header": {
                "type": "none"
              }
            },
            "sockopt": {
              "mark": 255,
              "tcpFastOpen": true,
              "tproxy": "off"
            }
          },
          "sniffing": {
            "enabled": true,
            "destOverride": ["http", "tls"]
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {},
          "tag": "direct"
        },
        {
          "protocol": "blackhole",
          "settings": {},
          "tag": "block"
        }
      ]
    }