apiVersion: v1
kind: ConfigMap
metadata:
  name: v2ray-config
data:
  config.json: |
    {
      "inbounds": [
        {
          "port": {{ .Values.v2ray.port }},
          "listen": "0.0.0.0",
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                "id": "{{ .Values.v2ray.uuid }}",
                "alterId": {{ .Values.v2ray.alterId }}
              }
            ]
          },
          "streamSettings": {
            "network": "{{ .Values.v2ray.network }}",
            "security": "{{ .Values.v2ray.security }}"
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }