apiVersion: v1
kind: Service
metadata:
  name: v2ray
  labels:
    app: v2ray
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.v2ray.port }}
    targetPort: {{ .Values.v2ray.port }}
    protocol: TCP
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: v2ray